# Generated by Django 4.1.2 on 2022-10-20 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registeruser',
            name='emailuser',
        ),
        migrations.AddField(
            model_name='registeruser',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='user_profiles'),
        ),
    ]
