# Generated by Django 4.1.2 on 2022-10-22 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_remove_registeruser_emailuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeruser',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
