# Generated by Django 4.0.7 on 2022-10-22 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_registeruser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeruser',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='registeruser',
            name='city',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='registeruser',
            name='pincode',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='registeruser',
            name='role',
            field=models.CharField(choices=[('1', 'Patient'), ('2', 'Doctor')], default='1', max_length=200),
        ),
        migrations.AddField(
            model_name='registeruser',
            name='state',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
