# Generated by Django 4.1.2 on 2022-10-22 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_registeruser_address_registeruser_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeruser',
            name='profile_picture',
            field=models.ImageField(db_column='<built-in function id>', null=True, upload_to=''),
        ),
    ]
