# Generated by Django 4.1.2 on 2022-10-22 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_alter_registeruser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeruser',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
