# Generated by Django 4.0.7 on 2022-10-22 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_alter_registeruser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeruser',
            name='role',
            field=models.CharField(choices=[('Patient', 'Patient'), ('Doctor', 'Doctor')], default='Patient', max_length=200),
        ),
    ]
