# Generated by Django 4.0.7 on 2022-10-22 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_alter_registeruser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeruser',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='registeruser',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='registeruser',
            name='pincode',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registeruser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='registeruser',
            name='state',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
